-d C:\Users\Sylvain\Documents\Gowin-Ministar-main\Gowin-Ministar-main\7segments_counter\fpga\impl\gwsynthesis\7segments.vg
-p GW1NS-4C-QFN48-7
-pn GW1NS-LV4CQN48C7/I6
-cst C:\Users\Sylvain\Documents\Gowin-Ministar-main\Gowin-Ministar-main\7segments_counter\fpga\src\7segments.cst
-cfg C:\Users\Sylvain\Documents\Gowin-Ministar-main\Gowin-Ministar-main\7segments_counter\fpga\impl\pnr\device.cfg
-bit
-tr
-ph
-sdf
-o
-timing
-cst_error
